SELECT Image_Metadata_cell_filename,
Image_Metadata_image_id,
Image_Metadata_cell_id,
Image_Metadata_wbc_type,
Image_AreaOccupied_AreaOccupied_IdentifyPrimaryObjects,
Image_AreaOccupied_Perimeter_IdentifyPrimaryObjects,
Image_AreaOccupied_TotalArea_IdentifyPrimaryObjects,
Image_Count_IdentifyPrimaryObjects,
Image_Granularity_10_OrigSaturation,
Image_Granularity_11_OrigSaturation,
Image_Granularity_12_OrigSaturation,
Image_Granularity_13_OrigSaturation,
Image_Granularity_14_OrigSaturation,
Image_Granularity_15_OrigSaturation,
Image_Granularity_16_OrigSaturation,
Image_Granularity_1_OrigSaturation,
Image_Granularity_2_OrigSaturation,
Image_Granularity_3_OrigSaturation,
Image_Granularity_4_OrigSaturation,
Image_Granularity_5_OrigSaturation,
Image_Granularity_6_OrigSaturation,
Image_Granularity_7_OrigSaturation,
Image_Granularity_8_OrigSaturation,
Image_Granularity_9_OrigSaturation,
Image_Height_BCCD,
Mean_IdentifyPrimaryObjects_Intensity_LowerQurtlIntnsty_OrgStrtn,
Mean_IdentifyPrimaryObjects_Intensity_MADIntensity_OrigSaturatin,
Mean_IdentifyPrimaryObjects_Intensity_MaxIntensity_OrigSaturatin,
Mean_IdentifyPrimaryObjects_Intensity_MeanIntensity_OrigSaturatn,
Mean_IdentifyPrimaryObjects_Intensity_MedianIntensity_OrigSatrtn,
Mean_IdentifyPrimaryObjects_Intensity_MinIntensity_OrigSaturatin,
Mean_IdentifyPrimaryObjects_Intensity_StdIntensity_OrigSaturatin,
Mean_IdentifyPrimaryObjects_Intensity_UpperQurtlIntnsty_OrgStrtn,
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_03_256,
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_00_256,
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_01_256,
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_02_256,
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_03_256,
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_00_256,
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_01_256,
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_02_256,
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_03_256,
Image_Threshold_FinalThreshold_IdentifyPrimaryObjects,
Image_Threshold_OrigThreshold_IdentifyPrimaryObjects,
Image_Threshold_SumOfEntropies_IdentifyPrimaryObjects,
Image_Threshold_WeightedVariance_IdentifyPrimaryObjects,
Image_Width_BCCD,
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_X_OrgStrtn,
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_Y_OrgStrtn,
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_Z_OrgStrtn,
Mean_IdentifyPrimaryObjects_Location_Center_X,
Mean_IdentifyPrimaryObjects_Location_Center_Y,
Mean_IdentifyPrimaryObjects_Location_Center_Z,
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_X_OrigSaturatn,
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_Y_OrigSaturatn,
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_Z_OrigSaturatn
FROM MyExpt_Per_Image 
WHERE (
Image_Metadata_cell_filename IS NOT NULL AND
Image_Metadata_image_id IS NOT NULL AND
Image_Metadata_cell_id IS NOT NULL AND
Image_Metadata_wbc_type IS NOT NULL AND
Image_AreaOccupied_AreaOccupied_IdentifyPrimaryObjects IS NOT NULL AND
Image_AreaOccupied_Perimeter_IdentifyPrimaryObjects IS NOT NULL AND
Image_AreaOccupied_TotalArea_IdentifyPrimaryObjects IS NOT NULL AND
Image_Count_IdentifyPrimaryObjects IS NOT NULL AND
Image_Granularity_10_OrigSaturation IS NOT NULL AND
Image_Granularity_11_OrigSaturation IS NOT NULL AND
Image_Granularity_12_OrigSaturation IS NOT NULL AND
Image_Granularity_13_OrigSaturation IS NOT NULL AND
Image_Granularity_14_OrigSaturation IS NOT NULL AND
Image_Granularity_15_OrigSaturation IS NOT NULL AND
Image_Granularity_16_OrigSaturation IS NOT NULL AND
Image_Granularity_1_OrigSaturation IS NOT NULL AND
Image_Granularity_2_OrigSaturation IS NOT NULL AND
Image_Granularity_3_OrigSaturation IS NOT NULL AND
Image_Granularity_4_OrigSaturation IS NOT NULL AND
Image_Granularity_5_OrigSaturation IS NOT NULL AND
Image_Granularity_6_OrigSaturation IS NOT NULL AND
Image_Granularity_7_OrigSaturation IS NOT NULL AND
Image_Granularity_8_OrigSaturation IS NOT NULL AND
Image_Granularity_9_OrigSaturation IS NOT NULL AND
Image_Height_BCCD IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_LowerQurtlIntnsty_OrgStrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_MADIntensity_OrigSaturatin IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_MaxIntensity_OrigSaturatin IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_MeanIntensity_OrigSaturatn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_MedianIntensity_OrigSatrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_MinIntensity_OrigSaturatin IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_StdIntensity_OrigSaturatin IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Intensity_UpperQurtlIntnsty_OrgStrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Txtr_AnglrScndMmnt_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Contrast_OrigSatrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Correlatin_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Textr_DffrncEntrpy_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_DffrncVrnc_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Entropy_OrigSaturtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas1_OrigStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_InfoMeas2_OrigStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimryObjcts_Txtr_InvrsDffrncMmnt_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumAverage_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumEntropy_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_SumVarianc_OrgStrtn_3_03_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_00_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_01_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_02_256 IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Texture_Variance_OrigSatrtn_3_03_256 IS NOT NULL AND
Image_Threshold_FinalThreshold_IdentifyPrimaryObjects IS NOT NULL AND
Image_Threshold_OrigThreshold_IdentifyPrimaryObjects IS NOT NULL AND
Image_Threshold_SumOfEntropies_IdentifyPrimaryObjects IS NOT NULL AND
Image_Threshold_WeightedVariance_IdentifyPrimaryObjects IS NOT NULL AND
Image_Width_BCCD IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_X_OrgStrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_Y_OrgStrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_CenterMssIntnsty_Z_OrgStrtn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_Center_X IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_Center_Y IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_Center_Z IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_X_OrigSaturatn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_Y_OrigSaturatn IS NOT NULL AND
Mean_IdentifyPrimaryObjects_Location_MaxIntensity_Z_OrigSaturatn IS NOT NULL)